// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dolgozo_Nyilvantartas;
//
//    var dolgozoNyilvantartasForm = DolgozoNyilvantartasForm.FromJson(jsonString);

namespace Dolgozo_NyilvantartasForm
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DolgozoNyilvantartasForm
    {
        [JsonProperty("id")]
        public long DolgozoNyilvantartasFormId { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string DolgozoNyilvantartasFormName { get; set; }

        [JsonProperty("salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? DolgozoNyilvantartasFormSalary { get; set; }

        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public string DolgozoNyilvantartasFormPosition { get; set; }

        [JsonProperty("Id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? Salary { get; set; }

        [JsonProperty("Position", NullValueHandling = NullValueHandling.Ignore)]
        public string Position { get; set; }

        [JsonProperty("Kiiratas", NullValueHandling = NullValueHandling.Ignore)]
        public string Kiiratas { get; set; }
    }

    public partial class DolgozoNyilvantartasForm
    {
        public static DolgozoNyilvantartasForm[] FromJson(string json) => JsonConvert.DeserializeObject<DolgozoNyilvantartasForm[]>(json, Dolgozo_NyilvantartasForm.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DolgozoNyilvantartasForm[] self) => JsonConvert.SerializeObject(self, Dolgozo_NyilvantartasForm.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
