// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Dolgozo_Nyilvantartas;
//
//    var dolgozoNyilvantartas = DolgozoNyilvantartas.FromJson(jsonString);

namespace Dolgozo_Nyilvantartas
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DolgozoNyilvantartas
    {
        [JsonProperty("id")]
        public long DolgozoNyilvantartaId { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string DolgozoNyilvantartaName { get; set; }

        [JsonProperty("salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? DolgozoNyilvantartaSalary { get; set; }

        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public string DolgozoNyilvantartaPosition { get; set; }

        [JsonProperty("Id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? Salary { get; set; }

        [JsonProperty("Position", NullValueHandling = NullValueHandling.Ignore)]
        public string Position { get; set; }

        [JsonProperty("Kiiratas", NullValueHandling = NullValueHandling.Ignore)]
        public string Kiiratas { get; set; }
    }

    public partial class DolgozoNyilvantartas
    {
        public static DolgozoNyilvantartas[] FromJson(string json) => JsonConvert.DeserializeObject<DolgozoNyilvantartas[]>(json, Dolgozo_Nyilvantartas.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DolgozoNyilvantartas[] self) => JsonConvert.SerializeObject(self, Dolgozo_Nyilvantartas.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
